import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Slot } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { formatAdminRetryCountdown } from "@/lib/admin-rate-limit";
import { trpc } from "@/lib/trpc";

export default function AdminWebOnlyLayout() { return Platform.OS === "web" ? <AdminCredentialGate /> : <NativeBlocked />; }

function AdminCredentialGate() {
  const credential = trpc.adminCredential.status.useQuery(undefined, { retry:false });
  const security = trpc.adminSecurity.status.useQuery(undefined, { enabled: Boolean(credential.data?.authenticated), retry:false });
  const signIn = trpc.adminCredential.signIn.useMutation({ onSuccess: () => void credential.refetch() });
  const begin = trpc.adminSecurity.beginMfaEnrollment.useMutation(); const confirm = trpc.adminSecurity.confirmMfaEnrollment.useMutation({ onSuccess: () => void security.refetch() }); const verify = trpc.adminSecurity.verifyMfaChallenge.useMutation({ onSuccess: () => void security.refetch() });
  const [username,setUsername]=useState(""); const [password,setPassword]=useState(""); const [code,setCode]=useState(""); const [enrollment,setEnrollment]=useState<{secret:string}|null>(null); const [recoveryCodes,setRecoveryCodes]=useState<string[]|null>(null); const [retrySeconds,setRetrySeconds]=useState<number|null>(null);
  useEffect(() => { if (retrySeconds === null || retrySeconds <= 0) return; const timer = setInterval(() => setRetrySeconds((value) => value === null ? null : Math.max(0, value - 1)), 1000); return () => clearInterval(timer); }, [retrySeconds]);
  async function submitCredential() { try { const result=await signIn.mutateAsync({ username, password }); if (result.rateLimited) { setRetrySeconds(result.retryAfterSeconds); setPassword(""); return; } setPassword(""); setRetrySeconds(null); } catch(error) { Alert.alert("Sign-in failed", error instanceof Error ? error.message : "Please retry."); } }
  if (credential.isLoading) return <Gate><ActivityIndicator color="#064B2C"/><Text style={styles.copy}>Checking Admin sign-in…</Text></Gate>;
  if (!credential.data?.authenticated) return <Gate><MaterialIcons name="lock" size={31} color="#064B2C"/><Text style={styles.title}>Admin staff sign-in</Text><Text style={styles.copy}>Enter your assigned username and password. Customer, Business, and Rider accounts cannot access this console.</Text>{!credential.data?.bootstrapConfigured ? <Text style={styles.warning}>Bootstrap Admin credentials have not been configured yet.</Text> : null}{retrySeconds !== null && retrySeconds > 0 ? <View style={styles.rateLimit}><MaterialIcons name="schedule" size={17} color="#8A5A00"/><View style={styles.rateCopy}><Text style={styles.rateTitle}>Sign-in temporarily paused</Text><Text style={styles.rateText}>Too many attempts. Try again in {formatAdminRetryCountdown(retrySeconds)}.</Text></View></View> : null}<TextInput editable={!retrySeconds} autoCapitalize="none" autoCorrect={false} value={username} onChangeText={setUsername} placeholder="Username" placeholderTextColor="#95A299" style={styles.input}/><TextInput editable={!retrySeconds} secureTextEntry value={password} onChangeText={setPassword} placeholder="Password" placeholderTextColor="#95A299" style={styles.input}/><Button disabled={!username || password.length < 12 || signIn.isPending || Boolean(retrySeconds && retrySeconds > 0)} label={signIn.isPending?"Signing in…":retrySeconds&&retrySeconds>0?`Try again in ${formatAdminRetryCountdown(retrySeconds)}`:"Continue"} onPress={() => void submitCredential()}/></Gate>;
  if (security.isLoading) return <Gate><ActivityIndicator color="#064B2C"/><Text style={styles.copy}>Applying Admin access controls…</Text></Gate>;
  if (security.error || !security.data) return <Gate><MaterialIcons name="block" size={31} color="#B54231"/><Text style={styles.title}>Admin access unavailable</Text><Text style={styles.copy}>Your credential session is not authorized for this Admin console.</Text></Gate>;
  const data=security.data as any;
  if (!data.request.hostAllowed) return <Gate><MaterialIcons name="language" size={31} color="#B54231"/><Text style={styles.title}>Use the dedicated Admin website</Text><Text style={styles.copy}>Open {data.canonicalHost.canonicalHost||"the configured Admin hostname"} to continue.</Text></Gate>;
  if (!data.request.ipAllowed) return <Gate><MaterialIcons name="wifi-off" size={31} color="#B54231"/><Text style={styles.title}>Network not allowlisted</Text><Text style={styles.copy}>Your current network is not authorized for the Admin console.</Text></Gate>;
  if (recoveryCodes) return <Gate><MaterialIcons name="key" size={31} color="#76500D"/><Text style={styles.title}>Save recovery codes</Text><Text style={styles.copy}>Store these single-use codes in your password manager. They cannot be shown again.</Text><View style={styles.codeGrid}>{recoveryCodes.map((value)=><Text key={value} style={styles.recoveryCode}>{value}</Text>)}</View><Button label="I stored these codes" onPress={()=>setRecoveryCodes(null)}/></Gate>;
  if (data.mfa.state!=="active") return <Gate><MaterialIcons name="phonelink-lock" size={31} color="#064B2C"/><Text style={styles.title}>Set up MFA</Text><Text style={styles.copy}>Add the secret to an authenticator app, then verify its six-digit code.</Text>{enrollment?<><Text style={styles.secret}>{enrollment.secret}</Text><TextInput keyboardType="number-pad" maxLength={6} value={code} onChangeText={setCode} placeholder="123456" placeholderTextColor="#95A299" style={styles.input}/><Button disabled={code.length!==6||confirm.isPending} label={confirm.isPending?"Confirming…":"Confirm MFA"} onPress={async()=>{const result=await confirm.mutateAsync({code});setRecoveryCodes(result.recoveryCodes);setCode("");}}/></>:<Button disabled={begin.isPending} label={begin.isPending?"Preparing…":"Start MFA setup"} onPress={async()=>setEnrollment(await begin.mutateAsync())}/>}</Gate>;
  if (!data.mfa.sessionActive) return <Gate><MaterialIcons name="security" size={31} color="#064B2C"/><Text style={styles.title}>Enter your MFA code</Text><Text style={styles.copy}>Use an authenticator or recovery code to unlock this Admin browser session.</Text><TextInput autoCapitalize="characters" value={code} onChangeText={(value)=>setCode(value.toUpperCase())} placeholder="123456 or ABCD1234" placeholderTextColor="#95A299" style={styles.input}/><Button disabled={!code||verify.isPending} label={verify.isPending?"Verifying…":"Verify and continue"} onPress={async()=>{await verify.mutateAsync({code});setCode("");}}/></Gate>;
  return <Slot/>;
}
function NativeBlocked(){return <ScreenContainer edges={["top","bottom","left","right"]}><View style={styles.page}><View style={styles.icon}><MaterialIcons name="desktop-windows" size={30} color="#064B2C"/></View><Text style={styles.title}>Admin console is web-only</Text><Text style={styles.copy}>Internal operations are available only through the protected Admin website.</Text></View></ScreenContainer>}
function Gate({children}:{children:React.ReactNode}){return <ScreenContainer edges={["top","bottom","left","right"]}><View style={styles.page}><View style={styles.icon}><MaterialIcons name="shield" size={30} color="#064B2C"/></View><View style={styles.gate}>{children}</View></View></ScreenContainer>}
function Button({label,onPress,disabled}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={({pressed})=>[styles.button,pressed&&styles.pressed,disabled&&styles.disabled]}><Text style={styles.buttonText}>{label}</Text></Pressable>}
const styles=StyleSheet.create({page:{flex:1,padding:28,alignItems:"center",justifyContent:"center",backgroundColor:"#F3F6F3"},gate:{width:"100%",maxWidth:360,alignItems:"center",gap:11},icon:{width:62,height:62,borderRadius:20,alignItems:"center",justifyContent:"center",backgroundColor:"#E0F4E7"},title:{marginTop:7,color:"#17251D",fontSize:21,lineHeight:27,fontWeight:"900",textAlign:"center"},copy:{color:"#66746B",fontSize:12,lineHeight:18,fontWeight:"600",textAlign:"center"},warning:{alignSelf:"stretch",padding:10,borderRadius:10,backgroundColor:"#FFF4DD",color:"#76500D",fontSize:10,fontWeight:"800",textAlign:"center"},rateLimit:{alignSelf:"stretch",padding:11,borderRadius:12,backgroundColor:"#FFF4DD",flexDirection:"row",gap:8,alignItems:"center"},rateCopy:{flex:1},rateTitle:{color:"#76500D",fontSize:11,fontWeight:"900"},rateText:{marginTop:2,color:"#8A5A00",fontSize:10,lineHeight:14,fontWeight:"700"},button:{alignSelf:"stretch",minHeight:44,marginTop:6,borderRadius:12,backgroundColor:"#064B2C",alignItems:"center",justifyContent:"center"},buttonText:{color:"#FFFFFF",fontSize:11,fontWeight:"900"},input:{alignSelf:"stretch",minHeight:45,paddingHorizontal:12,borderRadius:12,borderWidth:1,borderColor:"#CFE0D4",backgroundColor:"#FFFFFF",color:"#17251D",textAlign:"center",fontSize:15,fontWeight:"900",letterSpacing:1},secret:{alignSelf:"stretch",padding:12,borderRadius:12,backgroundColor:"#FFF4DD",color:"#4C3300",fontSize:16,letterSpacing:1.4,fontWeight:"900",textAlign:"center"},codeGrid:{alignSelf:"stretch",flexDirection:"row",flexWrap:"wrap",gap:7,justifyContent:"center"},recoveryCode:{minWidth:92,paddingVertical:7,paddingHorizontal:8,borderRadius:8,backgroundColor:"#FFF4DD",color:"#4C3300",fontSize:11,fontWeight:"900",textAlign:"center"},pressed:{opacity:0.78,transform:[{scale:0.985}]},disabled:{opacity:0.5}});
