import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { trpc } from "@/lib/trpc";

const percent = (bps: number | null | undefined) => bps === null || bps === undefined ? "—" : `${(bps / 100).toFixed(1)}%`;
export default function AdminAiQualityScreen() {
  const metrics = trpc.adminOperations.aiTriageQualityMetrics.useQuery(undefined, { retry: false });
  const data = metrics.data as any;
  if (metrics.isLoading) return <ScreenContainer><View style={styles.center}><ActivityIndicator color="#064B2C" /><Text style={styles.muted}>Loading AI quality metrics…</Text></View></ScreenContainer>;
  if (metrics.error || !data) return <ScreenContainer><View style={styles.center}><MaterialIcons name="lock-outline" size={28} color="#B54231" /><Text style={styles.title}>Quality monitoring requires senior operator access</Text><Text style={styles.muted}>Aggregate model metrics are restricted to senior operations.</Text></View></ScreenContainer>;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><ScrollView contentContainerStyle={styles.page} showsVerticalScrollIndicator={false}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={20} color="#064B2C" /></Pressable><View><Text style={styles.kicker}>HUMAN-LABELED QUALITY</Text><Text style={styles.title}>AI triage quality</Text></View></View><View style={styles.notice}><MaterialIcons name="shield" size={18} color="#064B2C" /><Text style={styles.noticeText}>Metrics use retained human outcome labels. They support monitoring and future policy review only; no automated retraining or deployment changes occur here.</Text></View><View style={styles.metrics}><Metric label="Assessments" value={String(data.assessmentCount)} /><Metric label="Feedback coverage" value={percent(data.feedbackCoverageBps)} /><Metric label="False positive" value={percent(data.falsePositiveRateBps)} /><Metric label="Avg. confidence" value={percent(data.averageConfidenceBps)} /></View><Text style={styles.section}>Human outcome labels</Text><View style={styles.card}>{Object.entries(data.feedbackCounts ?? {}).map(([label, value]) => <View key={label} style={styles.labelRow}><Text style={styles.label}>{label.replace(/_/g, " ")}</Text><Text style={styles.value}>{String(value)}</Text></View>)}</View><Text style={styles.section}>By model</Text>{data.byModel?.length ? data.byModel.map((model: any) => <View key={model.model} style={styles.card}><Text style={styles.model}>{model.model}</Text><Text style={styles.meta}>{model.assessmentCount} assessments · {model.labeledCount} labeled</Text><View style={styles.modelMetrics}><Text style={styles.modelMetric}>False positive: {percent(model.falsePositiveRateBps)}</Text><Text style={styles.modelMetric}>Confidence: {percent(model.averageConfidenceBps)}</Text></View></View>) : <View style={styles.card}><Text style={styles.muted}>No AI assessments have been retained yet.</Text></View>}<View style={styles.feedbackHint}><MaterialIcons name="tips-and-updates" size={18} color="#4C3300" /><Text style={styles.feedbackHintText}>To label a false positive, open an assessed photo report or emergency case, human-review the advisory outcome, then record feedback from its case detail.</Text></View></ScrollView></ScreenContainer>;
}
function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ page:{ backgroundColor:"#F3F6F3", padding:17, paddingBottom:34, alignSelf:"center", width:"100%", maxWidth:900 }, center:{ flex:1, backgroundColor:"#F3F6F3", alignItems:"center", justifyContent:"center", padding:28, gap:10 }, header:{ flexDirection:"row", alignItems:"center", gap:10 }, back:{ width:39, height:39, borderRadius:12, backgroundColor:"#E0F4E7", alignItems:"center", justifyContent:"center" }, kicker:{ color:"#168A4A", fontSize:9, letterSpacing:0.7, fontWeight:"900" }, title:{ marginTop:2, color:"#17251D", fontSize:20, fontWeight:"900" }, notice:{ marginTop:14, padding:12, borderRadius:14, backgroundColor:"#EAF3EC", borderWidth:1, borderColor:"#D4E6D9", flexDirection:"row", gap:8, alignItems:"flex-start" }, noticeText:{ flex:1, color:"#526158", fontSize:10, lineHeight:15, fontWeight:"600" }, metrics:{ marginTop:14, flexDirection:"row", gap:8, flexWrap:"wrap" }, metric:{ minWidth:134, flexGrow:1, padding:12, borderRadius:14, backgroundColor:"#FFFFFF", borderWidth:1, borderColor:"#DCE6DE" }, metricValue:{ color:"#064B2C", fontSize:18, fontWeight:"900" }, metricLabel:{ marginTop:3, color:"#66746B", fontSize:9, fontWeight:"800" }, section:{ marginTop:17, color:"#17251D", fontSize:14, fontWeight:"900" }, card:{ marginTop:8, padding:13, borderRadius:15, backgroundColor:"#FFFFFF", borderWidth:1, borderColor:"#DCE6DE" }, labelRow:{ flexDirection:"row", justifyContent:"space-between", paddingVertical:6, borderBottomWidth:1, borderBottomColor:"#EEF2EF" }, label:{ color:"#526158", fontSize:10, fontWeight:"800", textTransform:"capitalize" }, value:{ color:"#17251D", fontSize:11, fontWeight:"900" }, model:{ color:"#17251D", fontSize:12, fontWeight:"900" }, meta:{ marginTop:4, color:"#66746B", fontSize:9, fontWeight:"700" }, modelMetrics:{ marginTop:9, flexDirection:"row", gap:10, flexWrap:"wrap" }, modelMetric:{ color:"#064B2C", fontSize:10, fontWeight:"900" }, feedbackHint:{ marginTop:15, padding:12, borderRadius:14, backgroundColor:"#FFF4DD", flexDirection:"row", gap:8, alignItems:"flex-start" }, feedbackHintText:{ flex:1, color:"#73561C", fontSize:10, lineHeight:15, fontWeight:"600" }, muted:{ color:"#6C7A70", fontSize:11, lineHeight:16, fontWeight:"600", textAlign:"center" } });
