import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { trpc } from "@/lib/trpc";

type BusinessRow = { application: { id: number; businessType: "restaurant" | "cloud_kitchen" | null; status: string; displayName: string | null; city: string | null }; detail: { displayName: string | null; city: string | null } | null };

export default function AdminBusinessApplicationsScreen() {
  const businessesQuery = trpc.adminBusiness.listBusinesses.useQuery(undefined, { retry: false });
  const suspend = trpc.adminBusiness.suspend.useMutation({ onSuccess: () => void businessesQuery.refetch() });
  const restore = trpc.adminBusiness.restore.useMutation({ onSuccess: () => void businessesQuery.refetch() });
  const [selected, setSelected] = useState<BusinessRow | null>(null);
  const [reason, setReason] = useState("");
  const businesses = (businessesQuery.data ?? []) as BusinessRow[];

  async function suspendSelected() {
    if (!selected) return;
    try { await suspend.mutateAsync({ applicationId: selected.application.id, reason }); setSelected(null); setReason(""); Alert.alert("Business suspended", "This emergency action stopped public Business access. It was not an approval decision."); } catch (error) { Alert.alert("Could not suspend Business", error instanceof Error ? error.message : "Try again."); }
  }
  async function restoreBusiness(applicationId: number) {
    try { await restore.mutateAsync({ applicationId }); Alert.alert("Business restored", "The owner can access the workspace again. The Business returns paused and controls its own publishing."); } catch (error) { Alert.alert("Could not restore Business", error instanceof Error ? error.message : "Try again."); }
  }
  if (businessesQuery.isLoading) return <ScreenContainer><View style={styles.center}><ActivityIndicator color="#168A4A" /><Text style={styles.muted}>Loading Business support tools…</Text></View></ScreenContainer>;
  if (businessesQuery.error) return <ScreenContainer><View style={styles.center}><MaterialIcons name="admin-panel-settings" size={29} color="#064B2C" /><Text style={styles.title}>Admin access required</Text><Text style={styles.muted}>These tools are limited to support and emergency suspension.</Text></View></ScreenContainer>;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={styles.page}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={21} color="#064B2C" /></Pressable><View><Text style={styles.kicker}>KHANA KARLO OPERATIONS</Text><Text style={styles.title}>Business support</Text></View></View><Text style={styles.intro}>Businesses activate and publish themselves. Use this screen only for emergency suspension or restoration.</Text>{selected ? <View style={styles.panel}><Text style={styles.panelTitle}>Emergency suspension</Text><Text style={styles.muted}>{selected.detail?.displayName || selected.application.displayName || "Business"}</Text><TextInput value={reason} onChangeText={setReason} placeholder="State the operational reason (minimum 10 characters)" placeholderTextColor="#9DA8A0" multiline style={styles.input} /><Pressable disabled={suspend.isPending || reason.trim().length < 10} onPress={() => void suspendSelected()} style={({ pressed }) => [styles.suspendButton, pressed && styles.pressed, (suspend.isPending || reason.trim().length < 10) && styles.disabled]}>{suspend.isPending ? <ActivityIndicator color="#FFFFFF" size="small" /> : <Text style={styles.suspendText}>Suspend Business</Text>}</Pressable><Pressable onPress={() => setSelected(null)} style={styles.cancelButton}><Text style={styles.cancelText}>Cancel</Text></Pressable></View> : <FlatList data={businesses} keyExtractor={(item) => String(item.application.id)} contentContainerStyle={styles.list} renderItem={({ item }) => { const isSuspended = item.application.status === "suspended"; return <View style={styles.card}><View style={styles.cardTop}><View style={styles.icon}><MaterialIcons name={item.application.businessType === "cloud_kitchen" ? "kitchen" : "storefront"} size={20} color="#064B2C" /></View><View style={styles.cardCopy}><Text style={styles.cardTitle}>{item.detail?.displayName || item.application.displayName || "Untitled Business"}</Text><Text style={styles.cardMeta}>{item.detail?.city || item.application.city || "City pending"}</Text></View><Text style={[styles.status, isSuspended && styles.statusSuspended]}>{isSuspended ? "SUSPENDED" : "ACTIVE"}</Text></View>{isSuspended ? <Pressable disabled={restore.isPending} onPress={() => void restoreBusiness(item.application.id)} style={styles.restoreButton}><Text style={styles.restoreText}>Restore to paused</Text></Pressable> : <Pressable onPress={() => { setSelected(item); setReason(""); }} style={styles.actionButton}><Text style={styles.actionText}>Emergency suspend</Text></Pressable>}</View>; }} />}</View></ScreenContainer>;
}

const styles = StyleSheet.create({ page: { flex: 1, padding: 16, backgroundColor: "#FFF8ED" }, center: { flex: 1, padding: 28, alignItems: "center", justifyContent: "center", gap: 12, backgroundColor: "#FFF8ED" }, header: { flexDirection: "row", alignItems: "center", gap: 11 }, back: { width: 40, height: 40, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#EAF3EC" }, kicker: { color: "#168A4A", fontSize: 9, letterSpacing: 0.8, fontWeight: "900" }, title: { color: "#17251D", fontSize: 21, lineHeight: 26, fontWeight: "900" }, intro: { marginTop: 14, marginBottom: 14, color: "#6B7A70", fontSize: 11, lineHeight: 16, fontWeight: "600" }, muted: { marginTop: 3, color: "#6B7A70", fontSize: 11, lineHeight: 16, fontWeight: "600", textAlign: "center" }, list: { paddingBottom: 32, gap: 10 }, card: { padding: 14, borderRadius: 19, borderWidth: 1, borderColor: "#E1E7DF", backgroundColor: "#FFFFFF" }, cardTop: { flexDirection: "row", alignItems: "center", gap: 10 }, icon: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: "#E0F4E7" }, cardCopy: { flex: 1 }, cardTitle: { color: "#17251D", fontSize: 14, fontWeight: "900" }, cardMeta: { marginTop: 3, color: "#6C7A70", fontSize: 10, fontWeight: "700" }, status: { color: "#17683A", fontSize: 8, letterSpacing: 0.5, fontWeight: "900" }, statusSuspended: { color: "#B54231" }, actionButton: { marginTop: 12, minHeight: 40, borderRadius: 12, backgroundColor: "#FFF0ED", alignItems: "center", justifyContent: "center" }, actionText: { color: "#B54231", fontSize: 10, fontWeight: "900" }, restoreButton: { marginTop: 12, minHeight: 40, borderRadius: 12, backgroundColor: "#E0F4E7", alignItems: "center", justifyContent: "center" }, restoreText: { color: "#064B2C", fontSize: 10, fontWeight: "900" }, panel: { marginTop: 15, padding: 16, borderRadius: 19, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#F1C7C1" }, panelTitle: { color: "#B54231", fontSize: 16, fontWeight: "900" }, input: { minHeight: 96, marginTop: 14, borderRadius: 14, borderWidth: 1, borderColor: "#E6D2CD", backgroundColor: "#FFFDFC", padding: 11, textAlignVertical: "top", color: "#17251D", fontSize: 12, fontWeight: "600" }, suspendButton: { marginTop: 12, minHeight: 46, borderRadius: 14, backgroundColor: "#B54231", alignItems: "center", justifyContent: "center" }, suspendText: { color: "#FFFFFF", fontSize: 11, fontWeight: "900" }, cancelButton: { marginTop: 8, minHeight: 42, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: "#F2F5F1" }, cancelText: { color: "#526158", fontSize: 11, fontWeight: "900" }, pressed: { opacity: 0.8, transform: [{ scale: 0.985 }] }, disabled: { opacity: 0.55 } });
