import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { trpc } from "@/lib/trpc";

export default function AdminSecurityScreen() {
  const [cidr, setCidr] = useState(""); const [label, setLabel] = useState("");
  const audit = trpc.adminSecurity.sessionAudit.useQuery(undefined, { retry:false }); const rules = trpc.adminSecurity.allowlist.useQuery(undefined, { retry:false });
  const create = trpc.adminSecurity.createAllowlistRule.useMutation({ onSuccess: () => { setCidr(""); setLabel(""); void rules.refetch(); } }); const update = trpc.adminSecurity.updateAllowlistRule.useMutation({ onSuccess: () => void rules.refetch() }); const revoke = trpc.adminSecurity.revokeSession.useMutation({ onSuccess: () => void audit.refetch() });
  async function addRule() { try { await create.mutateAsync({ cidr, label }); } catch (error) { Alert.alert("Allowlist update failed", error instanceof Error ? error.message : "Please retry."); } }
  if (audit.isLoading || rules.isLoading) return <ScreenContainer><View style={styles.center}><ActivityIndicator color="#064B2C" /><Text style={styles.muted}>Loading security audit…</Text></View></ScreenContainer>;
  if (audit.error || rules.error || !audit.data || !rules.data) return <ScreenContainer><View style={styles.center}><MaterialIcons name="lock-outline" size={28} color="#B54231" /><Text style={styles.title}>Security audit access required</Text></View></ScreenContainer>;
  const data = audit.data as any; const allowlist = rules.data as any[];
  return <ScreenContainer edges={["top","bottom","left","right"]}><ScrollView contentContainerStyle={styles.page}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={20} color="#064B2C" /></Pressable><View><Text style={styles.kicker}>WEB ADMIN SECURITY</Text><Text style={styles.title}>Sessions & access audit</Text></View></View><View style={styles.metrics}><Metric label="Active sessions" value={data.summary.activeSessions}/><Metric label="Failed MFA" value={data.summary.failedMfaAttempts}/><Metric label="Denied networks" value={data.summary.deniedNetworks}/></View><Text style={styles.section}>IP allowlist</Text><View style={styles.card}><TextInput value={cidr} onChangeText={setCidr} placeholder="203.0.113.0/24" placeholderTextColor="#91A097" style={styles.input}/><TextInput value={label} onChangeText={setLabel} placeholder="Office network label" placeholderTextColor="#91A097" style={styles.input}/><Pressable disabled={!cidr || label.length < 3 || create.isPending} onPress={() => void addRule()} style={styles.button}><Text style={styles.buttonText}>Add allowlist rule</Text></Pressable></View>{allowlist.map((rule) => <View key={rule.id} style={styles.row}><View style={styles.flex}><Text style={styles.rowTitle}>{rule.cidr}</Text><Text style={styles.meta}>{rule.label} · {rule.status}</Text></View><Pressable onPress={() => void update.mutateAsync({ ruleId: rule.id, status: rule.status === "active" ? "disabled" : "active" })} style={styles.small}><Text style={styles.smallText}>{rule.status === "active" ? "Disable" : "Enable"}</Text></Pressable></View>)}<Text style={styles.section}>Trusted sessions</Text>{data.sessions.map((session:any) => <View key={session.id} style={styles.row}><View style={styles.flex}><Text style={styles.rowTitle}>Admin #{session.userId} · {session.ipAddress}</Text><Text style={styles.meta}>Expires {new Date(session.expiresAt).toLocaleString("en-PK", { dateStyle:"medium", timeStyle:"short" })}{session.revokedAt ? " · revoked" : ""}</Text></View>{!session.revokedAt ? <Pressable onPress={() => void revoke.mutateAsync({ sessionId: session.id })} style={styles.small}><Text style={styles.smallText}>Revoke</Text></Pressable> : null}</View>)}<Text style={styles.section}>Recent login attempts</Text>{data.loginAttempts.map((attempt:any) => <View key={attempt.id} style={styles.row}><View style={styles.flex}><Text style={styles.rowTitle}>{attempt.eventType.replace(/_/g," ")} · {attempt.success ? "allowed" : "denied"}</Text><Text style={styles.meta}>{attempt.ipAddress} · {new Date(attempt.createdAt).toLocaleString("en-PK", { dateStyle:"medium", timeStyle:"short" })}</Text></View></View>)}</ScrollView></ScreenContainer>;
}
function Metric({label,value}:{label:string;value:number}){return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>}
const styles=StyleSheet.create({page:{backgroundColor:"#F3F6F3",padding:17,paddingBottom:34,alignSelf:"center",width:"100%",maxWidth:900},center:{flex:1,backgroundColor:"#F3F6F3",alignItems:"center",justifyContent:"center",gap:10},header:{flexDirection:"row",alignItems:"center",gap:10},back:{width:39,height:39,borderRadius:12,backgroundColor:"#E0F4E7",alignItems:"center",justifyContent:"center"},kicker:{color:"#168A4A",fontSize:9,letterSpacing:.7,fontWeight:"900"},title:{marginTop:2,color:"#17251D",fontSize:20,fontWeight:"900"},metrics:{marginTop:15,flexDirection:"row",gap:8,flexWrap:"wrap"},metric:{minWidth:120,flexGrow:1,padding:12,borderRadius:14,backgroundColor:"#FFFFFF",borderWidth:1,borderColor:"#DCE6DE"},metricValue:{color:"#064B2C",fontSize:18,fontWeight:"900"},metricLabel:{marginTop:3,color:"#66746B",fontSize:9,fontWeight:"800"},section:{marginTop:17,color:"#17251D",fontSize:14,fontWeight:"900"},card:{marginTop:8,padding:12,borderRadius:14,backgroundColor:"#FFFFFF",borderWidth:1,borderColor:"#DCE6DE",gap:8},input:{minHeight:40,paddingHorizontal:10,borderRadius:10,borderWidth:1,borderColor:"#DCE6DE",color:"#17251D",fontSize:10,fontWeight:"700"},button:{minHeight:40,borderRadius:10,backgroundColor:"#064B2C",alignItems:"center",justifyContent:"center"},buttonText:{color:"#FFFFFF",fontSize:10,fontWeight:"900"},row:{marginTop:8,padding:12,borderRadius:13,backgroundColor:"#FFFFFF",borderWidth:1,borderColor:"#DCE6DE",flexDirection:"row",gap:8,alignItems:"center"},flex:{flex:1},rowTitle:{color:"#17251D",fontSize:11,fontWeight:"900",textTransform:"capitalize"},meta:{marginTop:3,color:"#66746B",fontSize:9,lineHeight:13,fontWeight:"700"},small:{minHeight:31,paddingHorizontal:9,borderRadius:9,backgroundColor:"#EFF3EF",justifyContent:"center"},smallText:{color:"#526158",fontSize:9,fontWeight:"900"},muted:{color:"#6C7A70",fontSize:11,fontWeight:"600"}});
