export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  adminWebHost: process.env.ADMIN_WEB_HOST ?? "",
  resendApiKey: process.env.RESEND_API_KEY ?? "",
  securityAlertFrom: process.env.SECURITY_ALERT_FROM ?? "",
  securityAlertTo: process.env.SECURITY_ALERT_TO ?? "",
  adminBootstrapUsername: process.env.ADMIN_BOOTSTRAP_USERNAME ?? "",
  adminBootstrapPassword: process.env.ADMIN_BOOTSTRAP_PASSWORD ?? "",
};
