import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { trpc } from "@/lib/trpc";

export default function NotificationInboxScreen() {
  const inbox = trpc.notifications.mine.useQuery(undefined, { retry: false, refetchInterval: 30_000 });
  const markRead = trpc.notifications.markRead.useMutation({ onSuccess: () => void inbox.refetch() });
  if (inbox.isLoading) return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={styles.center}><ActivityIndicator color="#168A4A" /><Text style={styles.muted}>Loading notifications…</Text></View></ScreenContainer>;
  const data = inbox.data;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><FlatList data={data?.notifications ?? []} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.list} ListHeaderComponent={<View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={21} color="#064B2C" /></Pressable><View><Text style={styles.title}>Notifications</Text><Text style={styles.subtitle}>{data?.unreadCount ?? 0} unread</Text></View></View>} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="notifications-none" size={30} color="#064B2C" /><Text style={styles.emptyTitle}>You’re up to date</Text><Text style={styles.muted}>Order, Rider-offer, support, and finance updates will appear here.</Text></View>} renderItem={({ item }) => <Pressable onPress={() => { void markRead.mutateAsync({ notificationId: item.id }); if (item.route) router.push(item.route as never); }} style={({ pressed }) => [styles.card, !item.readAt && styles.unread, pressed && styles.pressed]}><View style={styles.icon}><MaterialIcons name={item.category === "support" ? "support-agent" : item.category === "finance" ? "receipt-long" : "notifications"} size={19} color="#17683A" /></View><View style={{ flex: 1 }}><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.cardBody}>{item.body}</Text><Text style={styles.cardTime}>{new Date(item.createdAt).toLocaleString()}</Text></View></Pressable>} /></ScreenContainer>;
}
const styles = StyleSheet.create({ list: { backgroundColor: "#F4F6F3", paddingBottom: 24 }, center: { flex: 1, alignItems: "center", justifyContent: "center", gap: 8, backgroundColor: "#F4F6F3" }, header: { padding: 16, backgroundColor: "#FFFFFF", flexDirection: "row", gap: 11, alignItems: "center" }, back: { width: 40, height: 40, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#EAF3EC" }, title: { color: "#17251D", fontSize: 17, fontWeight: "900" }, subtitle: { marginTop: 2, color: "#6C7A70", fontSize: 10, fontWeight: "700" }, card: { marginHorizontal: 16, marginTop: 9, padding: 13, borderRadius: 16, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E1E6E0", flexDirection: "row", gap: 10 }, unread: { borderColor: "#9DDCB0", backgroundColor: "#F4FFF6" }, icon: { width: 37, height: 37, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "#EAF3EC" }, cardTitle: { color: "#17251D", fontSize: 12, fontWeight: "900" }, cardBody: { marginTop: 3, color: "#5E6D63", fontSize: 10, lineHeight: 14, fontWeight: "600" }, cardTime: { marginTop: 6, color: "#849087", fontSize: 8, fontWeight: "700" }, empty: { margin: 16, padding: 30, borderRadius: 20, alignItems: "center", gap: 8, backgroundColor: "#FFFFFF" }, emptyTitle: { color: "#17251D", fontSize: 15, fontWeight: "900" }, muted: { color: "#6C7A70", textAlign: "center", fontSize: 10, lineHeight: 15, fontWeight: "600" }, pressed: { opacity: 0.8 } });
