import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { trpc } from "@/lib/trpc";

const labelByType = { commission_reserved: "Commission reserved", commission_released: "Commission released", cash_collected: "COD collected", cash_variance: "COD variance", settlement_adjustment: "Cash remittance" } as const;
const formatPkr = (minor: number) => `PKR ${(minor / 100).toLocaleString("en-PK", { maximumFractionDigits: 2 })}`;

export default function RiderCashAccountScreen() {
  const account = trpc.orders.riderCashAccount.useQuery(undefined, { retry: false });
  const custody = trpc.orders.riderCashCustodySummary.useQuery(undefined, { retry: false });
  const remit = trpc.orders.remitRiderCash.useMutation({ onSuccess: () => { void account.refetch(); void custody.refetch(); } });
  if (account.isLoading || custody.isLoading) return <ScreenContainer><View style={styles.loading}><ActivityIndicator color="#168A4A" /><Text style={styles.muted}>Loading Cash Account…</Text></View></ScreenContainer>;
  const balance = account.data?.account.balanceMinor ?? 0; const openCustody = custody.data?.openCustodyMinor ?? 0; const entries = account.data?.entries ?? [];
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={21} color="#064B2C" /></Pressable><Text style={styles.headerTitle}>Cash Account</Text><View style={{ width: 40 }} /></View>
    <View style={styles.hero}><Text style={styles.eyebrow}>CURRENT ACCOUNT BALANCE</Text><Text style={styles.balance}>{formatPkr(balance)}</Text><Text style={styles.heroText}>Commission is reserved on COD acceptance. Confirmed cash and remittances are recorded in the immutable ledger below.</Text></View>
    <View style={styles.summary}><View><Text style={styles.label}>Open COD custody</Text><Text style={styles.value}>{formatPkr(openCustody)}</Text></View><View style={styles.divider} /><View><Text style={styles.label}>This week collected</Text><Text style={styles.value}>{formatPkr(custody.data?.weekCollectedMinor ?? 0)}</Text></View></View>
    {openCustody > 0 ? <Pressable disabled={remit.isPending} onPress={() => void remit.mutateAsync({ amountMinor: openCustody })} style={({ pressed }) => [styles.remit, pressed && { opacity: 0.86 }, remit.isPending && { opacity: 0.55 }]}><Text style={styles.remitText}>Settle open custody · {formatPkr(openCustody)}</Text><MaterialIcons name="payments" size={18} color="#FFFFFF" /></Pressable> : <View style={styles.settled}><MaterialIcons name="verified" size={18} color="#17683A" /><Text style={styles.settledText}>No COD custody is awaiting settlement.</Text></View>}
    <Text style={styles.section}>Account history</Text><Text style={styles.sectionHint}>Every entry is recorded by the delivery and settlement workflow.</Text>
    {entries.length ? entries.map((entry) => <View key={entry.id} style={styles.entry}><View style={styles.entryIcon}><MaterialIcons name={entry.amountMinor >= 0 ? "south-west" : "north-east"} size={18} color={entry.amountMinor >= 0 ? "#17683A" : "#A44A00"} /></View><View style={{ flex: 1 }}><Text style={styles.entryTitle}>{labelByType[entry.entryType]}</Text><Text style={styles.entryMeta}>{new Date(entry.createdAt).toLocaleString("en-PK", { dateStyle: "medium", timeStyle: "short" })}{entry.orderId ? ` · Order #${entry.orderId}` : ""}</Text></View><View style={{ alignItems: "flex-end" }}><Text style={[styles.entryAmount, entry.amountMinor < 0 && styles.debit]}>{entry.amountMinor >= 0 ? "+" : ""}{formatPkr(entry.amountMinor)}</Text><Text style={styles.balanceAfter}>Balance {formatPkr(entry.balanceAfterMinor)}</Text></View></View>) : <View style={styles.empty}><MaterialIcons name="receipt-long" size={25} color="#91A097" /><Text style={styles.emptyTitle}>No account entries yet</Text><Text style={styles.muted}>Accepted COD jobs and cash settlements will appear here.</Text></View>}
  </ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content:{ backgroundColor:"#F4F6F3", paddingBottom:32 }, header:{ height:74, paddingHorizontal:16, backgroundColor:"#FFFFFF", borderBottomWidth:1, borderBottomColor:"#E1E6E0", flexDirection:"row", alignItems:"center", justifyContent:"space-between" }, back:{ width:40, height:40, borderRadius:13, backgroundColor:"#EAF3EC", alignItems:"center", justifyContent:"center" }, headerTitle:{ color:"#17251D", fontSize:17, fontWeight:"900" }, hero:{ margin:16, padding:20, borderRadius:22, backgroundColor:"#064B2C" }, eyebrow:{ color:"#C8E1CF", fontSize:10, fontWeight:"900", letterSpacing:0.7 }, balance:{ marginTop:7, color:"#FFFFFF", fontSize:30, fontWeight:"900" }, heroText:{ marginTop:8, color:"#C8E1CF", fontSize:11, lineHeight:16, fontWeight:"600" }, summary:{ marginHorizontal:16, borderRadius:18, padding:15, backgroundColor:"#FFFFFF", borderWidth:1, borderColor:"#E1E6E0", flexDirection:"row", justifyContent:"space-between" }, label:{ color:"#6C7A70", fontSize:10, fontWeight:"700" }, value:{ marginTop:4, color:"#17251D", fontSize:14, fontWeight:"900" }, divider:{ width:1, backgroundColor:"#E1E6E0" }, remit:{ margin:16, marginTop:11, minHeight:48, borderRadius:14, backgroundColor:"#064B2C", alignItems:"center", justifyContent:"center", flexDirection:"row", gap:8 }, remitText:{ color:"#FFFFFF", fontSize:12, fontWeight:"900" }, settled:{ margin:16, marginTop:11, padding:13, borderRadius:14, backgroundColor:"#E0F4E7", flexDirection:"row", alignItems:"center", gap:8 }, settledText:{ color:"#17683A", fontSize:11, fontWeight:"800" }, section:{ marginHorizontal:16, marginTop:8, color:"#17251D", fontSize:15, fontWeight:"900" }, sectionHint:{ marginHorizontal:16, marginTop:3, marginBottom:9, color:"#6C7A70", fontSize:10, lineHeight:14, fontWeight:"600" }, entry:{ marginHorizontal:16, padding:13, backgroundColor:"#FFFFFF", borderBottomWidth:1, borderBottomColor:"#EDF0EC", flexDirection:"row", alignItems:"center", gap:10 }, entryIcon:{ width:36, height:36, borderRadius:12, backgroundColor:"#EAF3EC", alignItems:"center", justifyContent:"center" }, entryTitle:{ color:"#17251D", fontSize:12, fontWeight:"900" }, entryMeta:{ marginTop:3, color:"#6C7A70", fontSize:9, fontWeight:"600" }, entryAmount:{ color:"#17683A", fontSize:11, fontWeight:"900" }, debit:{ color:"#A44A00" }, balanceAfter:{ marginTop:3, color:"#6C7A70", fontSize:8, fontWeight:"600" }, empty:{ margin:16, padding:25, borderRadius:18, backgroundColor:"#FFFFFF", alignItems:"center", gap:7 }, emptyTitle:{ color:"#17251D", fontSize:13, fontWeight:"900" }, muted:{ color:"#6C7A70", fontSize:11, fontWeight:"600" }, loading:{ flex:1, alignItems:"center", justifyContent:"center", gap:10, backgroundColor:"#F4F6F3" } });
