import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { trpc } from "@/lib/trpc";

const money = (value: number) => `PKR ${(value / 100).toLocaleString("en-PK", { maximumFractionDigits: 2 })}`;

export default function RiderStatementScreen() {
  const statement = trpc.orders.riderStatement.useQuery(undefined, { retry: false });
  if (statement.isLoading) return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={styles.center}><ActivityIndicator color="#168A4A" /><Text style={styles.muted}>Loading your authoritative statement…</Text></View></ScreenContainer>;
  if (statement.error || !statement.data) return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={styles.center}><Text style={styles.title}>Rider statement unavailable</Text><Text style={styles.muted}>Return to your profile and try again.</Text></View></ScreenContainer>;
  const data = statement.data;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><FlatList data={data.entries} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.list} ListHeaderComponent={<><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={21} color="#064B2C" /></Pressable><Text style={styles.title}>Rider statement</Text><View style={{ width: 40 }} /></View><View style={styles.summary}><Text style={styles.kicker}>CASH CUSTODY — NOT EARNINGS</Text><Text style={styles.amount}>{money(data.totals.cashCustodyOpenMinor)}</Text><Text style={styles.copy}>Open custody awaiting controlled remittance. Rider compensation remains unavailable until a payout policy is approved.</Text><View style={styles.metrics}><Metric label="Collected" value={money(data.totals.cashCollectedMinor)} /><Metric label="Remitted" value={money(data.totals.cashCustodySettledMinor)} /></View></View><Text style={styles.section}>Financial events</Text></>} ListEmptyComponent={<View style={styles.empty}><Text style={styles.muted}>No financial events yet.</Text></View>} renderItem={({ item }) => <View style={styles.row}><View style={styles.icon}><MaterialIcons name="receipt-long" size={18} color="#17683A" /></View><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{item.entryType.replace(/_/g, " ")}</Text><Text style={styles.rowMeta}>{item.status} · {new Date(item.createdAt).toLocaleDateString()}</Text></View><Text style={styles.rowAmount}>{money(item.amountMinor)}</Text></View>} /></ScreenContainer>;
}

function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text></View>; }

const styles = StyleSheet.create({ list: { backgroundColor: "#F4F6F3", paddingBottom: 24 }, center: { flex: 1, alignItems: "center", justifyContent: "center", gap: 8, backgroundColor: "#F4F6F3" }, header: { height: 70, paddingHorizontal: 16, backgroundColor: "#FFFFFF", flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, back: { width: 40, height: 40, borderRadius: 13, backgroundColor: "#EAF3EC", alignItems: "center", justifyContent: "center" }, title: { color: "#17251D", fontSize: 17, fontWeight: "900" }, muted: { color: "#6C7A70", textAlign: "center", fontSize: 11, fontWeight: "700" }, summary: { margin: 16, padding: 17, borderRadius: 20, backgroundColor: "#064B2C" }, kicker: { color: "#A9DDB5", fontSize: 9, letterSpacing: 0.6, fontWeight: "900" }, amount: { marginTop: 5, color: "#FFFFFF", fontSize: 25, fontWeight: "900" }, copy: { marginTop: 7, color: "#C8E1CF", fontSize: 10, lineHeight: 15, fontWeight: "600" }, metrics: { marginTop: 14, flexDirection: "row", gap: 9 }, metric: { flex: 1, padding: 10, borderRadius: 12, backgroundColor: "#17683A" }, metricLabel: { color: "#C8E1CF", fontSize: 8, fontWeight: "800" }, metricValue: { marginTop: 3, color: "#FFFFFF", fontSize: 11, fontWeight: "900" }, section: { marginHorizontal: 16, marginBottom: 9, color: "#17251D", fontSize: 14, fontWeight: "900" }, row: { marginHorizontal: 16, marginBottom: 8, padding: 12, borderRadius: 15, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E1E6E0", flexDirection: "row", gap: 10, alignItems: "center" }, icon: { width: 35, height: 35, borderRadius: 11, backgroundColor: "#EAF3EC", alignItems: "center", justifyContent: "center" }, rowTitle: { color: "#17251D", fontSize: 11, fontWeight: "900", textTransform: "capitalize" }, rowMeta: { marginTop: 2, color: "#6C7A70", fontSize: 9, fontWeight: "700", textTransform: "capitalize" }, rowAmount: { color: "#064B2C", fontSize: 11, fontWeight: "900" }, empty: { margin: 16, padding: 24, borderRadius: 16, backgroundColor: "#FFFFFF" } });
