import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import MapView, { Marker, Polyline } from "react-native-maps";
import { StyleSheet, Text, View } from "react-native";

type Point = { latitudeE6: number; longitudeE6: number };
const coordinate = (point: Point) => ({ latitude: point.latitudeE6 / 1_000_000, longitude: point.longitudeE6 / 1_000_000 });

export function DeliveryTrackingMap({ rider, destination, freshnessSeconds, etaMinutes, routeAvailable }: { rider: Point | null; destination: Point | null; freshnessSeconds: number | null; etaMinutes?: number | null; routeAvailable?: boolean }) {
  if (!destination) return <View style={styles.unavailable}><MaterialIcons name="map" size={23} color="#52705B" /><Text style={styles.unavailableTitle}>Map unavailable for this address</Text><Text style={styles.unavailableText}>The saved delivery address does not yet include a map coordinate.</Text></View>;
  const destinationCoordinate = coordinate(destination);
  const riderCoordinate = rider ? coordinate(rider) : null;
  const region = riderCoordinate ? { latitude: (destinationCoordinate.latitude + riderCoordinate.latitude) / 2, longitude: (destinationCoordinate.longitude + riderCoordinate.longitude) / 2, latitudeDelta: Math.max(Math.abs(destinationCoordinate.latitude - riderCoordinate.latitude) * 2.2, 0.012), longitudeDelta: Math.max(Math.abs(destinationCoordinate.longitude - riderCoordinate.longitude) * 2.2, 0.012) } : { ...destinationCoordinate, latitudeDelta: 0.015, longitudeDelta: 0.015 };
  return <View style={styles.shell}><MapView style={styles.map} initialRegion={region} showsCompass={false} showsUserLocation={false} toolbarEnabled={false}><Marker coordinate={destinationCoordinate} title="Delivery address" pinColor="#FF6B00" />{riderCoordinate ? <Marker coordinate={riderCoordinate} title="Your Rider" description={freshnessSeconds !== null ? `Updated ${freshnessSeconds < 60 ? `${freshnessSeconds}s` : `${Math.floor(freshnessSeconds / 60)}m`} ago` : undefined} pinColor="#168A4A" /> : null}{riderCoordinate ? <Polyline coordinates={[riderCoordinate, destinationCoordinate]} strokeColor="#168A4A" strokeWidth={3} lineDashPattern={[7, 5]} /> : null}</MapView><View style={styles.caption}><MaterialIcons name={rider ? "my-location" : "schedule"} size={14} color="#17683A" /><Text style={styles.captionText}>{rider ? etaMinutes ? `Live Rider position. Estimated route time: ${etaMinutes} min.` : routeAvailable === false ? "Live Rider position. Route ETA is temporarily unavailable." : "Live Rider position. Calculating route ETA…" : "Waiting for the Rider to start delivery location sharing."}</Text></View></View>;
}

const styles = StyleSheet.create({ shell: { overflow: "hidden", borderRadius: 18, borderWidth: 1, borderColor: "#B6E2C4", backgroundColor: "#F4FFF6" }, map: { height: 220, width: "100%" }, caption: { minHeight: 38, paddingHorizontal: 11, flexDirection: "row", gap: 6, alignItems: "center" }, captionText: { flex: 1, color: "#41664C", fontSize: 9, lineHeight: 13, fontWeight: "700" }, unavailable: { minHeight: 124, borderRadius: 18, borderWidth: 1, borderColor: "#E1E6E0", backgroundColor: "#FAFCFA", alignItems: "center", justifyContent: "center", paddingHorizontal: 24 }, unavailableTitle: { marginTop: 8, color: "#294234", fontSize: 12, fontWeight: "900" }, unavailableText: { marginTop: 3, color: "#6C7A70", textAlign: "center", fontSize: 10, lineHeight: 14, fontWeight: "600" } });
