import { and, desc, eq, isNull } from "drizzle-orm";
import { auditEvents, customerAddresses, domainOutboxEvents } from "../drizzle/schema";
import type { CustomerAddressCreateInput, CustomerAddressUpdateInput } from "./modules/contracts/addresses";
import { DomainError } from "./modules/gateway/domain-error";
import { getDb } from "./db";

async function requireDb() { const db = await getDb(); if (!db) throw new DomainError("UNAVAILABLE", "Address services are temporarily unavailable."); return db; }
function key(type: string, id: number) { return `${type}:${id}:${crypto.randomUUID()}`; }
async function owned(db: any, userId: number, addressId: number) { const address = (await db.select().from(customerAddresses).where(and(eq(customerAddresses.id, addressId), eq(customerAddresses.userId, userId), isNull(customerAddresses.archivedAt))).limit(1))[0]; if (!address) throw new DomainError("NOT_FOUND", "Saved address not found."); return address; }

export async function listCustomerAddresses(userId: number) { const db = await requireDb(); return db.select().from(customerAddresses).where(and(eq(customerAddresses.userId, userId), isNull(customerAddresses.archivedAt))).orderBy(desc(customerAddresses.isDefault), desc(customerAddresses.updatedAt)); }
export async function createCustomerAddress(userId: number, input: CustomerAddressCreateInput) { const db = await requireDb(); return db.transaction(async (tx) => { const existing = await tx.select().from(customerAddresses).where(and(eq(customerAddresses.userId, userId), isNull(customerAddresses.archivedAt))); const isDefault = input.makeDefault || existing.length === 0; if (isDefault) await tx.update(customerAddresses).set({ isDefault: false }).where(and(eq(customerAddresses.userId, userId), isNull(customerAddresses.archivedAt))); await tx.insert(customerAddresses).values({ userId, label: input.label, recipientName: input.recipientName, phoneE164: input.phoneE164, addressLine1: input.addressLine1, addressLine2: input.addressLine2 ?? null, city: input.city, instructions: input.instructions ?? null, latitudeE6: input.latitudeE6, longitudeE6: input.longitudeE6, geocodeSource: input.geocodeSource, isDefault }); const address = (await tx.select().from(customerAddresses).where(and(eq(customerAddresses.userId, userId), eq(customerAddresses.label, input.label), isNull(customerAddresses.archivedAt))).orderBy(desc(customerAddresses.id)).limit(1))[0]; if (!address) throw new DomainError("INTERNAL", "Address could not be saved."); await tx.insert(auditEvents).values({ actorUserId: userId, entityType: "customer_address", entityId: String(address.id), action: "customer_address_created", nextValue: JSON.stringify({ label: address.label, city: address.city }) }); await tx.insert(domainOutboxEvents).values({ domain: "addresses", eventType: "customer_address.created", aggregateType: "customer_address", aggregateId: String(address.id), payload: JSON.stringify({ addressId: address.id, userId, city: address.city }), deduplicationKey: key("customer_address.created", address.id) }); return address; }); }
export async function updateCustomerAddress(userId: number, input: CustomerAddressUpdateInput) { const db = await requireDb(); return db.transaction(async (tx) => { const address = await owned(tx, userId, input.addressId); await tx.update(customerAddresses).set({ label: input.label, recipientName: input.recipientName, phoneE164: input.phoneE164, addressLine1: input.addressLine1, addressLine2: input.addressLine2 ?? null, city: input.city, instructions: input.instructions ?? null, latitudeE6: input.latitudeE6, longitudeE6: input.longitudeE6, geocodeSource: input.geocodeSource }).where(eq(customerAddresses.id, address.id)); await tx.insert(auditEvents).values({ actorUserId: userId, entityType: "customer_address", entityId: String(address.id), action: "customer_address_updated" }); await tx.insert(domainOutboxEvents).values({ domain: "addresses", eventType: "customer_address.updated", aggregateType: "customer_address", aggregateId: String(address.id), payload: JSON.stringify({ addressId: address.id, userId }), deduplicationKey: key("customer_address.updated", address.id) }); return owned(tx, userId, address.id); }); }
export async function setDefaultCustomerAddress(userId: number, addressId: number) { const db = await requireDb(); return db.transaction(async (tx) => { const address = await owned(tx, userId, addressId); await tx.update(customerAddresses).set({ isDefault: false }).where(and(eq(customerAddresses.userId, userId), isNull(customerAddresses.archivedAt))); await tx.update(customerAddresses).set({ isDefault: true }).where(eq(customerAddresses.id, address.id)); await tx.insert(auditEvents).values({ actorUserId: userId, entityType: "customer_address", entityId: String(address.id), action: "customer_address_defaulted" }); return { success: true } as const; }); }
export async function archiveCustomerAddress(userId: number, addressId: number) { const db = await requireDb(); return db.transaction(async (tx) => { const address = await owned(tx, userId, addressId); const active = await tx.select().from(customerAddresses).where(and(eq(customerAddresses.userId, userId), isNull(customerAddresses.archivedAt))); if (active.length <= 1) throw new DomainError("CONFLICT", "Keep at least one saved delivery address."); await tx.update(customerAddresses).set({ archivedAt: new Date(), isDefault: false }).where(eq(customerAddresses.id, address.id)); if (address.isDefault) { const replacement = active.find((candidate: typeof customerAddresses.$inferSelect) => candidate.id !== address.id); if (replacement) await tx.update(customerAddresses).set({ isDefault: true }).where(eq(customerAddresses.id, replacement.id)); } await tx.insert(auditEvents).values({ actorUserId: userId, entityType: "customer_address", entityId: String(address.id), action: "customer_address_archived" }); return { success: true } as const; }); }
