import { and, eq } from "drizzle-orm";
import { domainOutboxEvents, orders, notificationPreferences, supportTickets } from "../drizzle/schema";
import { getDb } from "./db";
import { DomainError } from "./modules/gateway/domain-error";

const key = (type: string, id: number) => `${type}:${id}:${crypto.randomUUID()}`;
async function dbOrThrow() { const db = await getDb(); if (!db) throw new DomainError("UNAVAILABLE", "Support is temporarily unavailable."); return db; }
export async function listSupportTickets(userId: number) { const db = await dbOrThrow(); return db.select().from(supportTickets).where(eq(supportTickets.customerUserId, userId)); }
export async function createSupportTicket(userId: number, input: { orderId?: number; category: "order" | "delivery" | "payment" | "account" | "other"; subject: string; message: string }) { const db = await dbOrThrow(); return db.transaction(async (tx) => { if (input.orderId) { const order = (await tx.select().from(orders).where(and(eq(orders.id, input.orderId), eq(orders.customerUserId, userId))).limit(1))[0]; if (!order) throw new DomainError("FORBIDDEN", "You can only request support for your own order."); } await tx.insert(supportTickets).values({ customerUserId: userId, ...input }); const ticket = (await tx.select().from(supportTickets).where(eq(supportTickets.customerUserId, userId)).orderBy(supportTickets.createdAt).limit(1))[0]; if (!ticket) throw new DomainError("INTERNAL", "Support ticket could not be created."); await tx.insert(domainOutboxEvents).values({ domain: "support", eventType: "support.ticket_created", aggregateType: "support_ticket", aggregateId: String(ticket.id), payload: JSON.stringify({ ticketId: ticket.id, customerUserId: userId, orderId: input.orderId ?? null }), deduplicationKey: key("support.ticket_created", ticket.id) }); return ticket; }); }
export async function getNotificationPreferences(userId: number) { const db = await dbOrThrow(); return (await db.select().from(notificationPreferences).where(eq(notificationPreferences.userId, userId)).limit(1))[0] ?? { orderUpdatesEnabled: true, supportUpdatesEnabled: true, promotionsEnabled: false }; }
export async function updateNotificationPreferences(userId: number, input: { orderUpdatesEnabled: boolean; supportUpdatesEnabled: boolean; promotionsEnabled: boolean }) { const db = await dbOrThrow(); await db.insert(notificationPreferences).values({ userId, ...input }).onDuplicateKeyUpdate({ set: { ...input, updatedAt: new Date() } }); return getNotificationPreferences(userId); }
