import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { useState } from "react";
import { Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { trpc } from "@/lib/trpc";

export default function SupportScreen() {
  const params = useLocalSearchParams<{ orderId?: string }>(); const linkedOrderId = Number(params.orderId);
  const tickets = trpc.support.mine.useQuery(undefined, { retry: false }); const create = trpc.support.create.useMutation({ onSuccess: () => void tickets.refetch() });
  const [open, setOpen] = useState(false); const [subject, setSubject] = useState(""); const [message, setMessage] = useState("");
  const submit = async () => { if (subject.trim().length < 3 || message.trim().length < 5) { Alert.alert("Add details", "Include a short subject and message."); return; } try { const ticket = await create.mutateAsync({ orderId: Number.isInteger(linkedOrderId) && linkedOrderId > 0 ? linkedOrderId : undefined, category: linkedOrderId ? "order" : "other", subject: subject.trim(), message: message.trim() }); setOpen(false); setSubject(""); setMessage(""); router.push(`/support/${ticket.id}` as never); } catch (error) { Alert.alert("Support request not sent", error instanceof Error ? error.message : "Try again."); } };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><FlatList data={tickets.data ?? []} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.list} ListHeaderComponent={<><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={21} color="#064B2C" /></Pressable><View style={{ flex: 1 }}><Text style={styles.title}>{linkedOrderId ? "Order support" : "Help & support"}</Text><Text style={styles.sub}>Only your own orders can be linked to a case.</Text></View><Pressable onPress={() => setOpen(!open)} style={styles.new}><Text style={styles.newText}>New case</Text></Pressable></View>{open ? <View style={styles.form}><TextInput value={subject} onChangeText={setSubject} placeholder="Subject" placeholderTextColor="#89958B" style={styles.input} /><TextInput value={message} onChangeText={setMessage} placeholder="Tell us what happened" placeholderTextColor="#89958B" multiline style={[styles.input, styles.message]} /><Pressable disabled={create.isPending} onPress={() => void submit()} style={styles.submit}><Text style={styles.submitText}>{create.isPending ? "Sending…" : "Create support case"}</Text></Pressable></View> : null}<Text style={styles.section}>Your support cases</Text></>} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="support-agent" size={30} color="#064B2C" /><Text style={styles.emptyTitle}>No support cases yet</Text><Text style={styles.sub}>Start a case here, or open support directly from an order.</Text></View>} renderItem={({ item }) => <Pressable onPress={() => router.push(`/support/${item.id}` as never)} style={styles.ticket}><View style={{ flex: 1 }}><Text style={styles.ticketTitle}>{item.subject}</Text><Text style={styles.ticketMeta}>{item.category} {item.orderId ? `· Order #${item.orderId}` : ""}</Text></View><Text style={styles.status}>{item.status.replace(/_/g, " ")}</Text></Pressable>} /></ScreenContainer>;
}
const styles = StyleSheet.create({ list: { backgroundColor: "#F4F6F3", paddingBottom: 25 }, header: { padding: 16, backgroundColor: "#FFFFFF", flexDirection: "row", alignItems: "center", gap: 10 }, back: { width: 40, height: 40, borderRadius: 13, backgroundColor: "#EAF3EC", alignItems: "center", justifyContent: "center" }, title: { color: "#17251D", fontSize: 17, fontWeight: "900" }, sub: { marginTop: 2, color: "#6C7A70", fontSize: 9, lineHeight: 13, fontWeight: "600" }, new: { paddingHorizontal: 10, paddingVertical: 8, borderRadius: 10, backgroundColor: "#064B2C" }, newText: { color: "#FFFFFF", fontSize: 10, fontWeight: "900" }, form: { margin: 16, padding: 13, borderRadius: 16, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#D9E3DA" }, input: { height: 42, paddingHorizontal: 10, borderRadius: 10, borderWidth: 1, borderColor: "#DDE5DE", color: "#17251D", fontSize: 11, fontWeight: "700" }, message: { height: 90, marginTop: 8, paddingTop: 10, textAlignVertical: "top" }, submit: { marginTop: 10, minHeight: 42, borderRadius: 11, alignItems: "center", justifyContent: "center", backgroundColor: "#168A4A" }, submitText: { color: "#FFFFFF", fontSize: 11, fontWeight: "900" }, section: { marginHorizontal: 16, marginBottom: 8, color: "#17251D", fontSize: 14, fontWeight: "900" }, ticket: { marginHorizontal: 16, marginBottom: 8, padding: 13, borderRadius: 15, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E1E6E0", flexDirection: "row", gap: 9 }, ticketTitle: { color: "#17251D", fontSize: 12, fontWeight: "900" }, ticketMeta: { marginTop: 3, color: "#6C7A70", fontSize: 9, fontWeight: "700", textTransform: "capitalize" }, status: { color: "#17683A", fontSize: 8, fontWeight: "900", textTransform: "uppercase" }, empty: { margin: 16, padding: 30, alignItems: "center", gap: 8, borderRadius: 18, backgroundColor: "#FFFFFF" }, emptyTitle: { color: "#17251D", fontSize: 14, fontWeight: "900" } });
