import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import * as Location from "expo-location";
import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { ScreenBack } from "@/components/khana-ui";
import { ScreenContainer } from "@/components/screen-container";
import { trpc } from "@/lib/trpc";

type Zone = { name: string; centerLatitudeE6: number | null; centerLongitudeE6: number | null; radiusMeters: number | null; courierBaseMinutes: number; courierMinutesPerKm: number };

export default function DeliveryZoneScreen() {
  const zoneQuery = trpc.businessOperations.deliveryZone.useQuery(undefined, { retry: false });
  const update = trpc.businessOperations.updateDeliveryZone.useMutation({ onSuccess: () => void zoneQuery.refetch() });
  const [name, setName] = useState(""); const [radiusKm, setRadiusKm] = useState("5"); const [baseMinutes, setBaseMinutes] = useState("8"); const [minutesPerKm, setMinutesPerKm] = useState("3"); const [latitudeE6, setLatitudeE6] = useState<number | null>(null); const [longitudeE6, setLongitudeE6] = useState<number | null>(null); const [pinning, setPinning] = useState(false);
  useEffect(() => { const zone = zoneQuery.data as Zone | undefined; if (!zone) return; setName(zone.name); setRadiusKm(String((zone.radiusMeters ?? 5_000) / 1_000)); setBaseMinutes(String(zone.courierBaseMinutes)); setMinutesPerKm(String(zone.courierMinutesPerKm)); setLatitudeE6(zone.centerLatitudeE6); setLongitudeE6(zone.centerLongitudeE6); }, [zoneQuery.data]);
  async function pin() { try { setPinning(true); if (!(await Location.hasServicesEnabledAsync())) throw new Error("Turn on Location Services and try again."); const permission = await Location.requestForegroundPermissionsAsync(); if (permission.status !== "granted") throw new Error("Location permission was not granted."); const current = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced }); setLatitudeE6(Math.round(current.coords.latitude * 1_000_000)); setLongitudeE6(Math.round(current.coords.longitude * 1_000_000)); } catch (error) { Alert.alert("Could not set pickup pin", error instanceof Error ? error.message : "Check location settings and try again."); } finally { setPinning(false); } }
  async function save() { try { if (latitudeE6 === null || longitudeE6 === null) throw new Error("Set the Restaurant pickup pin first."); const radius = Math.round(Number(radiusKm) * 1_000); const base = Number(baseMinutes); const perKm = Number(minutesPerKm); if (!name.trim() || !Number.isInteger(radius) || radius < 500 || !Number.isInteger(base) || base < 1 || !Number.isInteger(perKm) || perKm < 1) throw new Error("Enter a zone name, a radius of at least 0.5 km, and whole-minute estimates."); await update.mutateAsync({ name: name.trim(), centerLatitudeE6: latitudeE6, centerLongitudeE6: longitudeE6, radiusMeters: radius, courierBaseMinutes: base, courierMinutesPerKm: perKm }); Alert.alert("Delivery zone updated", "Customer checkout will now verify distance against this radius and show a transparent estimate."); } catch (error) { Alert.alert("Could not update delivery zone", error instanceof Error ? error.message : "Try again."); } }
  if (zoneQuery.isLoading) return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={styles.center}><ActivityIndicator color="#168A4A" /><Text style={styles.muted}>Loading delivery-zone controls…</Text></View></ScreenContainer>;
  if (zoneQuery.error) return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={styles.center}><MaterialIcons name="lock" size={28} color="#064B2C" /><Text style={styles.errorTitle}>Approved Business access required</Text><Text style={styles.muted}>Only the Business owner can configure service-zone delivery rules.</Text></View></ScreenContainer>;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={styles.page}><ScreenBack title="Delivery zone & ETA" /><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Customer delivery coverage</Text><Text style={styles.subtitle}>Use the actual Restaurant or Cloud Kitchen pickup point. Checkout will reject deliveries outside the radius and preserve the resulting distance and estimate with each order.</Text><View style={styles.card}><Text style={styles.label}>Delivery zone name</Text><TextInput value={name} onChangeText={setName} placeholder="e.g. Islamabad core" placeholderTextColor="#9AA69E" style={styles.input} /><Text style={styles.label}>Pickup point</Text><Pressable disabled={pinning} onPress={() => void pin()} style={({ pressed }) => [styles.pin, pressed && styles.pressed, pinning && styles.disabled]}>{pinning ? <ActivityIndicator color="#064B2C" size="small" /> : <MaterialIcons name={latitudeE6 === null ? "location-searching" : "my-location"} size={20} color="#064B2C" />}<View><Text style={styles.pinTitle}>{latitudeE6 === null ? "Set pickup pin" : "Pickup pin saved"}</Text><Text style={styles.pinSub}>{latitudeE6 === null ? "Use your current position at the outlet or kitchen" : `${(latitudeE6 / 1_000_000).toFixed(5)}, ${(longitudeE6! / 1_000_000).toFixed(5)}`}</Text></View></Pressable><Field label="Delivery radius (km)" value={radiusKm} onChangeText={setRadiusKm} /><Field label="Base courier time (minutes)" value={baseMinutes} onChangeText={setBaseMinutes} /><Field label="Additional minutes per km" value={minutesPerKm} onChangeText={setMinutesPerKm} /><View style={styles.note}><MaterialIcons name="info-outline" size={18} color="#934403" /><Text style={styles.noteText}>Customer ETA = the slowest live dish preparation time + your configured base courier time + the configured minutes per kilometre from this pickup pin.</Text></View><Pressable disabled={update.isPending} onPress={() => void save()} style={({ pressed }) => [styles.save, pressed && styles.pressed, update.isPending && styles.disabled]}>{update.isPending ? <ActivityIndicator color="#FFFFFF" size="small" /> : <><MaterialIcons name="save" size={18} color="#FFFFFF" /><Text style={styles.saveText}>Save delivery-zone rules</Text></>}</Pressable></View></ScrollView></View></ScreenContainer>;
}
function Field({ label, value, onChangeText }: { label: string; value: string; onChangeText: (value: string) => void }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} keyboardType="decimal-pad" style={styles.input} /></View>; }
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: "#FFF8ED", paddingHorizontal: 16, paddingTop: 6 }, content: { paddingBottom: 28 }, center: { flex: 1, paddingHorizontal: 30, alignItems: "center", justifyContent: "center", backgroundColor: "#FFF8ED", gap: 10 }, title: { marginTop: 14, color: "#17251D", fontSize: 24, fontWeight: "900" }, subtitle: { marginTop: 5, color: "#66766B", fontSize: 11, lineHeight: 17, fontWeight: "600" }, card: { marginTop: 19, padding: 14, borderRadius: 20, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E1E9E0" }, label: { color: "#526158", marginTop: 10, marginBottom: 5, fontSize: 9, fontWeight: "900" }, input: { height: 43, paddingHorizontal: 11, borderRadius: 12, backgroundColor: "#FBFCFA", borderWidth: 1, borderColor: "#DDE5DC", color: "#17251D", fontSize: 12, fontWeight: "700" }, pin: { minHeight: 62, paddingHorizontal: 12, borderRadius: 14, backgroundColor: "#E0F4E7", flexDirection: "row", alignItems: "center", gap: 9 }, pinTitle: { color: "#064B2C", fontSize: 11, fontWeight: "900" }, pinSub: { color: "#52705B", marginTop: 2, fontSize: 9, fontWeight: "700" }, field: { marginTop: 1 }, note: { marginTop: 14, padding: 11, borderRadius: 13, backgroundColor: "#FFF0E6", flexDirection: "row", gap: 8, alignItems: "flex-start" }, noteText: { flex: 1, color: "#934403", fontSize: 9, lineHeight: 13, fontWeight: "700" }, save: { marginTop: 14, minHeight: 46, borderRadius: 14, backgroundColor: "#064B2C", flexDirection: "row", gap: 8, alignItems: "center", justifyContent: "center" }, saveText: { color: "#FFFFFF", fontSize: 11, fontWeight: "900" }, muted: { color: "#66766B", fontSize: 11, lineHeight: 16, textAlign: "center", fontWeight: "600" }, errorTitle: { color: "#17251D", fontSize: 17, fontWeight: "900" }, pressed: { opacity: 0.75, transform: [{ scale: 0.985 }] }, disabled: { opacity: 0.6 } });
