import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { trpc } from "@/lib/trpc";

export default function BusinessHomeScreen() {
  const operations = trpc.businessOperations.mine.useQuery(undefined, { retry: false });
  if (operations.isLoading) return <ScreenContainer><View style={styles.center}><ActivityIndicator color="#168A4A" /><Text style={styles.copy}>Loading your authorised Business workspace…</Text></View></ScreenContainer>;
  if (operations.error) return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={styles.center}><View style={styles.lock}><MaterialIcons name="lock" size={27} color="#064B2C" /></View><Text style={styles.title}>Business approval required</Text><Text style={styles.copy}>Your Restaurant or Cloud Kitchen operations open only after Khana KarLo approval.</Text><Pressable onPress={() => router.replace("/account/workspaces" as never)} style={styles.primary}><Text style={styles.primaryText}>View application status</Text></Pressable></View></ScreenContainer>;
  if (!operations.data) return <ScreenContainer><View style={styles.center}><ActivityIndicator color="#168A4A" /><Text style={styles.copy}>Preparing your Business workspace…</Text></View></ScreenContainer>;
  const data = operations.data; const kitchen = data.kitchens[0]; const outlet = data.outlets[0]; const isKitchen = Boolean(kitchen);
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={styles.page}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={21} color="#064B2C" /></Pressable><View><Text style={styles.kicker}>ACTIVE BUSINESS WORKSPACE</Text><Text style={styles.title}>{data.organisation.displayName}</Text></View></View><View style={styles.hero}><View style={styles.heroIcon}><MaterialIcons name={isKitchen ? "kitchen" : "storefront"} size={29} color="#FFFFFF" /></View><Text style={styles.heroTitle}>{isKitchen ? "Kitchen Control" : "Restaurant Live Orders"}</Text><Text style={styles.heroCopy}>{isKitchen ? `${kitchen?.name} is approved. Control brands, stations, capacity, and order routing.` : `${outlet?.name} is approved. Manage live orders, menu availability, outlet readiness, and staff.`}</Text><Pressable onPress={() => router.push("/merchant/orders" as never)} style={styles.primary}><Text style={styles.primaryText}>{isKitchen ? "Open Kitchen queue" : "Open Live Orders"}</Text><MaterialIcons name="arrow-forward" size={18} color="#FFFFFF" /></Pressable></View><View style={styles.status}><MaterialIcons name="verified" size={19} color="#168A4A" /><Text style={styles.statusText}>Approval is active. Your production records are stored securely in Khana KarLo Business.</Text></View></View></ScreenContainer>;
}

const styles = StyleSheet.create({ page: { flex: 1, padding: 16, backgroundColor: "#FFF8ED" }, center: { flex: 1, padding: 28, alignItems: "center", justifyContent: "center", gap: 12, backgroundColor: "#FFF8ED" }, lock: { width: 56, height: 56, borderRadius: 18, backgroundColor: "#E0F4E7", alignItems: "center", justifyContent: "center" }, header: { flexDirection: "row", gap: 11, alignItems: "center" }, back: { width: 40, height: 40, borderRadius: 13, backgroundColor: "#EAF3EC", alignItems: "center", justifyContent: "center" }, kicker: { color: "#168A4A", fontSize: 9, letterSpacing: 0.75, fontWeight: "900" }, title: { color: "#17251D", fontSize: 22, lineHeight: 27, fontWeight: "900" }, hero: { marginTop: 24, padding: 21, borderRadius: 24, backgroundColor: "#064B2C" }, heroIcon: { width: 57, height: 57, borderRadius: 18, backgroundColor: "#168A4A", alignItems: "center", justifyContent: "center" }, heroTitle: { marginTop: 16, color: "#FFFFFF", fontSize: 21, fontWeight: "900" }, heroCopy: { marginTop: 7, color: "#D9E8DC", fontSize: 12, lineHeight: 18, fontWeight: "600" }, primary: { marginTop: 19, minHeight: 50, paddingHorizontal: 16, borderRadius: 15, flexDirection: "row", gap: 7, alignItems: "center", justifyContent: "center", backgroundColor: "#FFB73D" }, primaryText: { color: "#17311E", fontSize: 12, fontWeight: "900" }, status: { marginTop: 14, padding: 14, borderRadius: 17, backgroundColor: "#FFFFFF", flexDirection: "row", gap: 10, alignItems: "flex-start", borderWidth: 1, borderColor: "#E1E8DF" }, statusText: { flex: 1, color: "#596B5E", fontSize: 11, lineHeight: 16, fontWeight: "700" }, copy: { color: "#687970", fontSize: 12, lineHeight: 18, fontWeight: "600", textAlign: "center" }, });
