import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Image as ExpoImage } from "expo-image";
import { router } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { trpc } from "@/lib/trpc";

type ManagedReview = { id: number; rating: number; publicComment: string | null; privateFeedback: string | null; feedbackTopics: string[]; businessReply: string | null; createdAt: Date; customerName: string; photos: { id: number; privacy: "public" | "business_only"; url: string }[] };

export default function BusinessReviewsScreen() {
  const reviews = trpc.businessReviews.mine.useQuery(undefined, { retry: false });
  const reply = trpc.businessReviews.reply.useMutation({ onSuccess: () => void reviews.refetch() });
  if (reviews.isLoading) return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={styles.center}><ActivityIndicator color="#168A4A" /></View></ScreenContainer>;
  if (reviews.error) return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={styles.center}><Text style={styles.title}>Business reviews are unavailable</Text><Pressable onPress={() => router.back()} style={styles.backButton}><Text style={styles.backText}>Back to workspace</Text></Pressable></View></ScreenContainer>;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={styles.screen}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={21} color="#064B2C" /></Pressable><View><Text style={styles.kicker}>CUSTOMER REPUTATION</Text><Text style={styles.title}>Reviews & feedback</Text></View></View><FlatList data={(reviews.data ?? []) as ManagedReview[]} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.list} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="star-border" size={35} color="#168A4A" /><Text style={styles.emptyTitle}>No reviews yet</Text><Text style={styles.emptyCopy}>Verified customer ratings will appear here after delivered orders.</Text></View>} renderItem={({ item }) => <ReviewCard review={item} pending={reply.isPending} onReply={async (value) => { try { await reply.mutateAsync({ reviewId: item.id, reply: value }); } catch (error) { Alert.alert("Could not save reply", error instanceof Error ? error.message : "Try again."); } }} />} /></View></ScreenContainer>;
}

function ReviewCard({ review, pending, onReply }: { review: ManagedReview; pending: boolean; onReply: (reply: string) => Promise<void> }) { const [reply, setReply] = useState(""); return <View style={styles.card}><View style={styles.cardTop}><View><Text style={styles.customer}>{review.customerName}</Text><Text style={styles.date}>{new Date(review.createdAt).toLocaleDateString("en-PK")}</Text></View><View style={styles.rating}><MaterialIcons name="star" size={15} color="#E5A10A" /><Text style={styles.ratingText}>{review.rating}.0</Text></View></View>{review.publicComment ? <Text style={styles.comment}>{review.publicComment}</Text> : null}{review.privateFeedback ? <View style={styles.private}><MaterialIcons name="lock" size={14} color="#7A5109" /><Text style={styles.privateText}>Private feedback: {review.privateFeedback}</Text></View> : null}{review.photos.length ? <View style={styles.photoRow}>{review.photos.map((photo) => <ExpoImage key={photo.id} source={photo.url} style={styles.reviewPhoto} contentFit="cover" />)}</View> : null}{review.feedbackTopics.length ? <Text style={styles.topics}>{review.feedbackTopics.join(" · ")}</Text> : null}{review.businessReply ? <View style={styles.reply}><Text style={styles.replyLabel}>YOUR REPLY</Text><Text style={styles.replyText}>{review.businessReply}</Text></View> : <View style={styles.replyForm}><TextInput value={reply} onChangeText={setReply} placeholder="Reply publicly to this verified review" placeholderTextColor="#879187" style={styles.replyInput} multiline maxLength={1000} /><Pressable disabled={!reply.trim() || pending} onPress={() => void onReply(reply.trim())} style={[styles.replyButton, (!reply.trim() || pending) && styles.replyDisabled]}><Text style={styles.replyButtonText}>{pending ? "Saving…" : "Post reply"}</Text></Pressable></View>}</View>; }

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: "#FFF8ED", paddingHorizontal: 16, paddingTop: 6 }, center: { flex: 1, alignItems: "center", justifyContent: "center", gap: 12, padding: 24, backgroundColor: "#FFF8ED" }, header: { flexDirection: "row", gap: 11, alignItems: "center", marginBottom: 14 }, back: { width: 40, height: 40, borderRadius: 13, backgroundColor: "#EAF3EC", alignItems: "center", justifyContent: "center" }, kicker: { color: "#168A4A", fontSize: 9, letterSpacing: 0.7, fontWeight: "900" }, title: { color: "#17251D", fontSize: 20, fontWeight: "900" }, list: { paddingBottom: 32 }, empty: { marginTop: 60, padding: 30, alignItems: "center", gap: 8, borderRadius: 20, backgroundColor: "#FFFFFF" }, emptyTitle: { color: "#17251D", fontSize: 15, fontWeight: "900" }, emptyCopy: { color: "#687970", fontSize: 11, textAlign: "center", lineHeight: 16, fontWeight: "600" }, card: { padding: 14, marginBottom: 10, borderRadius: 18, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E1E8DF" }, cardTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, customer: { color: "#17251D", fontSize: 12, fontWeight: "900" }, date: { marginTop: 2, color: "#78867B", fontSize: 9, fontWeight: "700" }, rating: { paddingHorizontal: 8, paddingVertical: 5, borderRadius: 9, backgroundColor: "#FFF0D5", flexDirection: "row", gap: 3, alignItems: "center" }, ratingText: { color: "#8C5000", fontSize: 10, fontWeight: "900" }, comment: { marginTop: 11, color: "#34443A", fontSize: 11, lineHeight: 16, fontWeight: "600" }, private: { marginTop: 10, padding: 10, borderRadius: 11, backgroundColor: "#FFF7E7", flexDirection: "row", gap: 6, alignItems: "flex-start" }, privateText: { flex: 1, color: "#735214", fontSize: 10, lineHeight: 14, fontWeight: "700" }, photoRow: { marginTop: 10, flexDirection: "row", gap: 7 }, reviewPhoto: { width: 62, height: 62, borderRadius: 10 }, topics: { marginTop: 9, color: "#168A4A", fontSize: 9, fontWeight: "900" }, reply: { marginTop: 12, padding: 10, borderRadius: 11, backgroundColor: "#EAF3EC" }, replyLabel: { color: "#168A4A", fontSize: 8, letterSpacing: 0.6, fontWeight: "900" }, replyText: { marginTop: 3, color: "#34533D", fontSize: 10, lineHeight: 15, fontWeight: "700" }, replyForm: { marginTop: 12 }, replyInput: { minHeight: 64, padding: 10, borderRadius: 11, borderWidth: 1, borderColor: "#E1E8DF", color: "#17251D", fontSize: 10, lineHeight: 14, textAlignVertical: "top" }, replyButton: { marginTop: 7, alignSelf: "flex-end", minHeight: 34, paddingHorizontal: 11, borderRadius: 10, justifyContent: "center", backgroundColor: "#064B2C" }, replyDisabled: { opacity: 0.5 }, replyButtonText: { color: "#FFFFFF", fontSize: 10, fontWeight: "900" }, backButton: { minHeight: 42, paddingHorizontal: 14, borderRadius: 12, justifyContent: "center", backgroundColor: "#064B2C" }, backText: { color: "#FFFFFF", fontSize: 11, fontWeight: "900" } });
